dataset_name: 'augmented'
target_dim: (96, 96)
dataset_path: '$ROOT/data/A28-87_CP_lvl1_HandE_1_Merged_RAW_ch00_augmented_patch_96x96/'
model_save_path: '$ROOT/checkpoints/aug_AutoEncoder_depth5_seed1.pty'
output_save_path: '$ROOT/results/aug_AutoEncoder_depth5_seed1/'
log_folder: '$ROOT/logs'
learning_rate: 1e-3
temp: 1.0
base_temp: 1.0
n_views: 2
contrast_mode: 'one'
aug_methods: 'rotation,uniform_stretch,directional_stretch,volume_preserving_stretch,partial_stretch'
max_epochs: 200
batch_size: 64
model: 'AutoEncoder'
num_filters: 32
num_workers: 4
random_seed: 1
train_val_test_ratio: '6:2:2'