data:
  dataset_name: 'augmented_MoNuSeg'
  train_name: 'MoNuSeg2018TrainData'
  test_name: 'MoNuSeg2018TestData'
  patch_size: [96, 96]
  aug_patch_size: [32, 32]
  sample_percent: 0.1
  aug_multiplier: 3
  organ_type: 'Colon'
aiae:
  num_workers: 4
reg2seg:
  train_pair: ['aug','non_mother_anchor'] # ['aug', 'mother'], []
  optimize_test: False