output_save_root: '../results/'
log_folder: '../logs'
learning_rate: 1e-3
max_epochs: 100
patience: 50
batch_size: 64
model: 'UNet'
num_filters: 64
num_workers: 4
random_seed: 1
train_val_test_ratio: '8:1:1'
n_plot_per_epoch: 3
wandb_entity: danqiliao