model_save_root: '../checkpoints/'
output_save_root: '../results/'
log_folder: '../logs'
learning_rate: 1e-3
latent_loss: 'SimCLR'
temp: 1.0
base_temp: 1.0
n_views: 2
contrast_mode: 'one'
max_epochs: 100
patience: 50
batch_size: 64
model: 'AutoEncoder'
num_filters: 32
depth: 5
pairing: ['aug','non_mother'] #['aug', 'mother']
num_workers: 4
random_seed: 1
train_val_test_ratio: '8:1:1'
wandb_entity: 'danqiliao'