dataset_name: 'augmented_MoNuSeg'
target_dim: (32, 32)
dataset_path: '$ROOT/data/MoNuSeg2018TrainData_augmented_patch_32x32/'
model_save_path: '$ROOT/checkpoints/aug_MoNuSeg_depth5_seed1_SimCLR.pty'
output_save_path: '$ROOT/results/aug_MoNuSeg_depth5_seed1_SimCLR/'
log_folder: '$ROOT/logs'
learning_rate: 1e-3
latent_loss: 'SimCLR'
temp: 1.0
base_temp: 1.0
n_views: 2
contrast_mode: 'one'
aug_methods: 'rotation,uniform_stretch,directional_stretch,volume_preserving_stretch,partial_stretch'
#aug_methods: 'rotation'
max_epochs: 200
patience: 50
batch_size: 64
model: 'AutoEncoder'
num_filters: 32
num_workers: 4
random_seed: 1
train_val_test_ratio: '6:2:2'